<%= rails_env %>:
  adapter: mysql
  database: <%= application %>_<%= rails_env %>
  username: <%= application %>
  password: <%= Capistrano::CLI.password_prompt("database password: ") %>
  host: localhost